// Generated by Dagger (https://google.github.io/dagger).
package com.karanchuk.roman.testtranslate.ui.translator.targetlang;

import com.google.gson.Gson;

import javax.inject.Provider;

import dagger.MembersInjector;

public final class TargetLangActivity_MembersInjector
    implements MembersInjector<TargetLangActivity> {
  private final Provider<Gson> mGsonProvider;

  public TargetLangActivity_MembersInjector(Provider<Gson> mGsonProvider) {
    this.mGsonProvider = mGsonProvider;
  }

  public static MembersInjector<TargetLangActivity> create(Provider<Gson> mGsonProvider) {
    return new TargetLangActivity_MembersInjector(mGsonProvider);
  }

  @Override
  public void injectMembers(TargetLangActivity instance) {
    injectMGson(instance, mGsonProvider.get());
  }

  public static void injectMGson(TargetLangActivity instance, Gson mGson) {
    instance.mGson = mGson;
  }
}
