// Generated by Dagger (https://google.github.io/dagger).
package com.karanchuk.roman.testtranslate.ui.translator.sourcelang;

import com.google.gson.Gson;

import javax.inject.Provider;

import dagger.MembersInjector;

public final class SourceLangActivity_MembersInjector
    implements MembersInjector<SourceLangActivity> {
  private final Provider<Gson> mGsonProvider;

  public SourceLangActivity_MembersInjector(Provider<Gson> mGsonProvider) {
    this.mGsonProvider = mGsonProvider;
  }

  public static MembersInjector<SourceLangActivity> create(Provider<Gson> mGsonProvider) {
    return new SourceLangActivity_MembersInjector(mGsonProvider);
  }

  @Override
  public void injectMembers(SourceLangActivity instance) {
    injectMGson(instance, mGsonProvider.get());
  }

  public static void injectMGson(SourceLangActivity instance, Gson mGson) {
    instance.mGson = mGson;
  }
}
