// Generated by Dagger (https://google.github.io/dagger).
package com.karanchuk.roman.testtranslate.ui.translator;

import com.google.gson.Gson;
import com.karanchuk.roman.testtranslate.data.repository.YandexDictionaryRepository;
import com.karanchuk.roman.testtranslate.data.repository.YandexTranslateRepository;

import javax.inject.Provider;

import dagger.MembersInjector;

public final class TranslatorPresenter_MembersInjector
    implements MembersInjector<TranslatorPresenter> {
  private final Provider<Gson> mGsonProvider;

  private final Provider<YandexTranslateRepository> mYandexTranslateRepositoryProvider;

  private final Provider<YandexDictionaryRepository> mYandexDictionaryRepositoryProvider;

  public TranslatorPresenter_MembersInjector(
      Provider<Gson> mGsonProvider,
      Provider<YandexTranslateRepository> mYandexTranslateRepositoryProvider,
      Provider<YandexDictionaryRepository> mYandexDictionaryRepositoryProvider) {
    this.mGsonProvider = mGsonProvider;
    this.mYandexTranslateRepositoryProvider = mYandexTranslateRepositoryProvider;
    this.mYandexDictionaryRepositoryProvider = mYandexDictionaryRepositoryProvider;
  }

  public static MembersInjector<TranslatorPresenter> create(
      Provider<Gson> mGsonProvider,
      Provider<YandexTranslateRepository> mYandexTranslateRepositoryProvider,
      Provider<YandexDictionaryRepository> mYandexDictionaryRepositoryProvider) {
    return new TranslatorPresenter_MembersInjector(
        mGsonProvider, mYandexTranslateRepositoryProvider, mYandexDictionaryRepositoryProvider);
  }

  @Override
  public void injectMembers(TranslatorPresenter instance) {
    injectMGson(instance, mGsonProvider.get());
    injectMYandexTranslateRepository(instance, mYandexTranslateRepositoryProvider.get());
    injectMYandexDictionaryRepository(instance, mYandexDictionaryRepositoryProvider.get());
  }

  public static void injectMGson(TranslatorPresenter instance, Gson mGson) {
    instance.mGson = mGson;
  }

  public static void injectMYandexTranslateRepository(
      TranslatorPresenter instance, YandexTranslateRepository mYandexTranslateRepository) {
    instance.mYandexTranslateRepository = mYandexTranslateRepository;
  }

  public static void injectMYandexDictionaryRepository(
      TranslatorPresenter instance, YandexDictionaryRepository mYandexDictionaryRepository) {
    instance.mYandexDictionaryRepository = mYandexDictionaryRepository;
  }
}
